language: perl
perl: 
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:
  # prevent "plelase tell me who you are errors for certain DZIL configs
  - git config --global user.name "Travis CI"

install:
  # Deal with all the DZIL dependencies, quickly and quietly
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  - cpanm --quiet --notest --skip-satisfied Pod::Markdown
  - cpanm --quiet --notest --skip-satisfied Pod::Coverage::TrustPod
  - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1 DBIC_NO_WARN_BAD_PERL=1
  - dzil listdeps | grep -vP '[^\w:]' | cpanm --quiet --notest --skip-satisfied
  - cpanm Text::Wrap

script:
  - dzil test
