language: perl
perl: 
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:
  # prevent "plelase tell me who you are errors for certain DZIL configs
  - git config --global user.name "Travis CI"

install:
  # Deal with all the DZIL dependencies, quickly and quietly
  - cpanm --notest Dist::Zilla
  - cpanm --notest Pod::Markdown
  - cpanm --notest Pod::Coverage::TrustPod
  - dzil authordeps | xargs -n 5 cpanm --notest
  - export DBIC_NO_WARN_BAD_PERL=1
  - dzil listdeps | xargs cpanm --verbose --notest

script:
  - dzil test --all
